# Site settings
title: Perez Productions
email: noah@perez.productions
url: https://perez.productions
description: "Director of Photography in Florida."
keywords: "video, videographer, cinematic, cinematographer, photography"
skills: "Director of Photography"
meta_author: LastName FirstName

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
 - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 000F34
#  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 000F34
  secondary-dark: 000F34

# Footer settings
footer:
  copyright: Perez Productions
#  location: Location
  social: Socials
#  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: youtube
    url: https://youtube.com/@Perez_Productions
  - title: instagram
    url: https://instagram.com/_the_noah_perez_
  - title: linkedin
    url: https://linkedin.com/in/noah-perez-fl/
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
#  - title: github
#    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
#  - line: Florida

# Credits content
#credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
